# Spring事务失效的原因

spring提供的声明式事务注解@Transactional，极大的方便了开发者管理事务，无需手动编写开启、提交、回滚事务的代码。

但是也带来了一些隐患，如果使用不当，可能导致事务不生效，最终导致脏数据入库。

## 哪些场景事务不生效

1. 数据库引擎不支持事务；
2. 没有被Spring管理；【不太可能】
3. 注解所在的方法是否为public；
4. 在同一个类中，非事务方法调用事务方法；
5. 所用数据源没有开启事务管理器；
6. 确保异常没有被try-catch，catch以后也不会生效；
7. 异常类型错误；
8. 事物的传播机制（propagration）不正确。



### 数据库引擎不支持事务

当选择引擎是MyISAM时，在正常配置的情况下，出现异常并不会导致事务回滚。



测试案例，先创建一个Spring Boot项目，添加MySQL和Mybatis相关依赖。

```xml
<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
</dependency>
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>2.2.0</version>
</dependency>
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-test</artifactId>
</dependency>
```

创建启动类TXApplication。

```java
@SpringBootApplication
@EnableTransactionManagement(proxyTargetClass = true)
public class TXApplication {

    public static void main(String[] args) {
        SpringApplication.run(TXApplication.class, args);
    }

}
```

创建一个Logo表

```mysql
create table logo (
  id int auto_increment primary key,
  path varchar(100) not null
)engine = MyISAM;
```

实体类、mapper、service画瓢即可，在LogoService添加addLogo方法，用于保存Logo信息。

```java
@Transactional
public void addLogo(Logo logo) {
    logoMapper.insert(logo);
    throw new RuntimeException();
}
```

添加测试类。

```java
@SpringBootTest
@RunWith(SpringRunner.class)
public class LogoServiceTests {
    @Autowired
    private LogoService logoService;
    @Test
    public void test1() {
        Logo logo = new Logo();
        logo.setId(12);
        logo.setPath("/tmp/logo.gif");
        logoService.addLogo(logo);
    }
}
```

我们在addLogo方法添加了事务注解，查看数据库表时，依旧将数据保存下来了。



### 注解所在的类未加载成bean

一般不太可能，因为Spring容器启动的时候，就会实例化该对象。



### 注解所在的方法不为公有的

一般不会出现，在编译器中会提示Methods annotated with '@Transactional' must be overridable 。



以下来自Spring官方文档：

```
When using proxies, you should apply the @Transactional annotation only to methods with public visibility. If you do annotate protected, private or package-visible methods with the @Transactional annotation, no error is raised, but the annotated method does not exhibit the configured transactional settings. Consider the use of AspectJ (see below) if you need to annotate non-public methods.
```

@Transaction只能用于public的方法上，否则事务不会生效；如果用在非public方法上，就可以开启AspectJ代理模式。



@Transactional是基于动态代理的，Spring的代理工厂在启动时会扫描所有的类和方法，并检查方法的修饰符是否为public，非public时不会获取@Transactional的属性信息，这时@Transactional的动态代理对象为空。



### 在同一个类中，一个非事务方法调用事务方法

在系统声明@Transaction的目标方法时，Spring Framework默认使用AOP代理，在代码运行时生成一个代理对象，再由这个代理对象【代理类在执行目标方法前后，加上了事务管理的代码】来统一管理；当在Service实现类直接调用内部方法时，其本质上是通过this对象来调用的方式【该方式并没有加上事务管理代码】，而不是代理对象，此时就会出现事务失效的情况。



例子：

```java
@Service
public class OrderServiceImpl implements OrderService {

    @Autowired
    private OrderMapper orderMapper;

    @Override
    public void saveOrder(Order order) {
        if (order == null) {
            return;
        }
        try {
            save(order);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Transactional(rollbackFor = RuntimeException.class)
    public void save(Order order) {
        orderMapper.insert(order);
        throw new RuntimeException();
    }
}
```

查看order表，发现依然将数据保存到数据库中，不应该回滚了吗？而且异常我也捕获了呀！此时就需要了解Transactional原理了，即上面所介绍的。



解决方式一：

```java
@Service
public class OrderServiceImpl implements OrderService {

    @Autowired
    private OrderMapper orderMapper;
  
  	@Autowired
  	private OrderService orderService;

    @Override
    public void saveOrder(Order order) {
        if (order == null) {
            return;
        }
        try {
            orderService.save(order);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Transactional(rollbackFor = RuntimeException.class)
  	@Override
    public void save(Order order) {
        orderMapper.insert(order);
        throw new RuntimeException();
    }
}
```

因为Spring通过三级缓存解决了循环依赖的问题，所以可注入自身bean对象。注入的OrderService由于是代理对象，该对象中的save方法进行了增强，使得事务进行了回滚操作。







### 所用数据源未开启事务管理器

在Spring环境中，需要注入事务管理Bean。

```java
@Bean
public PlatformTransactionManager transactionManager(DataSource dataSource) {
    return new DataSourceTransactionManager(dataSource);
}
```

在Spring Boot环境中，添加一个注解即可。

```java
@EnableTransactionManagement(proxyTargetClass = true)
```

如果未注册该Bean到Spring容器中，那么所有的事务都将会失效。



### 异常被吃了

Spring是根据抛出的异常来回滚的，如果异常被捕获了没有抛出的话，事务就不会回滚。

事务正常回滚

```java
@Transactional(rollbackFor = RuntimeException.class)
@Override
public void save(Order order) {
    orderMapper.insert(order);
    throw new RuntimeException();
}
```

不回滚，相当于执行该方法未发生异常，因为被catch住了，使得Spring不进行事务回滚。

```java
@Transactional(rollbackFor = RuntimeException.class)
@Override
public void save(Order order) {
    try {
        orderMapper.insert(order);
        throw new RuntimeException();
    } catch (Exception e) {
        e.printStackTrace();
    }
}
```

不回滚【不太理解，为啥不回滚】

```java
@Transactional(rollbackFor = RuntimeException.class)
@Override
public void save(Order order) {
    try {
        orderMapper.insert(order);
    } catch (Exception e) {
        e.printStackTrace();
        throw new RuntimeException();
    }
}
```



因为：

```java
if (txAttr == null || !(ptm instanceof CallbackPreferringPlatformTransactionManager)) {
  // Standard transaction demarcation with getTransaction and commit/rollback calls.
  TransactionInfo txInfo = createTransactionIfNecessary(ptm, txAttr, joinpointIdentification);

  Object retVal;
  try {
    // This is an around advice: Invoke the next interceptor in the chain.
    // This will normally result in a target object being invoked.
    retVal = invocation.proceedWithInvocation();
  }
  catch (Throwable ex) {
    // target invocation exception
    completeTransactionAfterThrowing(txInfo, ex);
    throw ex;
  }
  finally {
    cleanupTransactionInfo(txInfo);
  }
}
```

这个是spring事务的部分源码，当我们业务代码进行捕获时，他是执行不到completeTransactionAfterThrowing，这个方法里面就是执行相应的回滚操作，相关源码如下

```java
if (txInfo.transactionAttribute != null && txInfo.transactionAttribute.rollbackOn(ex)) {
    try {
      txInfo.getTransactionManager().rollback(txInfo.getTransactionStatus());
    }
    catch (TransactionSystemException ex2) {
      logger.error("Application exception overridden by rollback exception", ex);
      ex2.initApplicationException(ex);
      throw ex2;
    }
    catch (RuntimeException | Error ex2) {
      logger.error("Application exception overridden by rollback exception", ex);
      throw ex2;
    }
}
```



### 事务的传播机制不正确

直接看例子

```java
@Service
public class OrderServiceImpl implements OrderService {

    @Autowired
    private OrderMapper orderMapper;
  
  	@Autowired
  	private OrderService orderService;

    @Override
  	@Transactional
    public void saveOrder(Order order) {
        if (order == null) {
            return;
        }
        try {
            orderService.save(order);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    @Transactional
  	@Override
    public void save(Order order) {
        orderMapper.insert(order);
        throw new RuntimeException();
    }
}
```

测试saveOrder方法，发生了回滚操作。之前不是说把异常捕获了，数据可以插入成功吗？

原因：Spring事务的默认传播行为是REQUIRED，如果当前存在事务，则加入该事务，如果当前不存在事务，则创建一个新的事务。

即save方法会加入到saveOrder的事务中，save和saveOrder属于同一个事务，因此save抛异常回滚，根据事务的原子性，saveOrder也会回滚。如果想让save抛出异常，saveOrder还能插入，可将save方法的事务传播行为设置为REQUIRES_NEW，此时saveOrder方法调用save方法时，必须进行捕获，否则save方法的异常将传递到saveOrder方法中，使得saveOrder也出现了异常，最终导致回滚。



相关链接：https://zhuanlan.zhihu.com/p/101396825

相关链接：https://www.guitu18.com/post/2019/10/30/56.html

相关链接：https://spring.hhui.top/spring-blog/2020/02/03/200203-SpringBoot%E7%B3%BB%E5%88%97%E6%95%99%E7%A8%8B%E4%B9%8B%E4%BA%8B%E5%8A%A1%E4%B8%8D%E7%94%9F%E6%95%88%E7%9A%84%E5%87%A0%E7%A7%8Dcase/

相关链接：https://www.imooc.com/article/317779